from argparse import ArgumentParser


parser = ArgumentParser("HMACL", add_help=False)
parser.add_argument("--env", type=str, default="m2ale", help="")
parser.add_argument("--name", type=str, default="vdn_ns", help="")
parser.add_argument("--t_update", type=int, default=1000, help="")
parser.add_argument("--improve_type", type=str, default="hard", help="")
parser.add_argument("--metrics", type=str, default="win_rate", help="")
parser.add_argument("--loss_coef", type=float, default=0.5, help="")
parser.add_argument("--temperature", type=float, default=0.5, help="")
# todo 层级放置到env_args下
# parser.add_argument("--map_size", type=list, default=[33, 33], help="")
# parser.add_argument("--num_agents", type=int, default=3, help="Number of agents")
# parser.add_argument("--wandb_suffix", type=str, default="-", help="A suffix append to last of wnadb name")
# parser.add_argument("--env")
# parser.add_argument("--wandb_group")
# parser.add_argument("--wandb_user_name")
# parser.add_argument("--wandb_job_type")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")

