from argparse import ArgumentParser


parser = ArgumentParser("HMACL")
parser.add_argument("--env_config_name", type=str, default="m2ale", help="")
parser.add_argument("--algo_config_name", type=str, default="vdn_ns", help="")
# parser.add_argument("--num_agents", type=int, default=3, help="Number of agents")
# parser.add_argument("--wandb_suffix", type=str, default="-", help="A suffix append to last of wnadb name")
# parser.add_argument("--env")
# parser.add_argument("--wandb_group")
# parser.add_argument("--wandb_user_name")
# parser.add_argument("--wandb_job_type")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")
# parser.add_argument("")

