from argparse import ArgumentParser


parser = ArgumentParser("HMACL")
parser.add_argument("--env")
parser.add_argument("--wandb_group")
parser.add_argument("--wandb_user_name")
parser.add_argument("--wandb_job_type")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")
parser.add_argument("")

