env: "m2ale"

env_args:
  scenario: "7u_vs_10u"
  time_limit: 200
  camp: "offensive"
  reward_type: "dense"
  map_size: [12, 12]
  tag_map_size: [50, 50]
  expand_d: 2
  pos_init_type: "random"
  obs_with_agent_id: True

test_greedy: True
test_nepisode: 100
eval_nepisode: 200
test_interval: 5000
eval_interval: 1000  # evaluate target task interval
log_interval: 400
runner_log_interval: 400
learner_log_interval: 400
t_max: 4000000
t_update: 100000
