env: "m2ale"

env_args:
  scenario: "5u_vs_5u"
  time_limit: 200
  camp: "offensive"
  reward_type: "dense"
  map_size: [10, 10]
  tag_map_size: [50, 50]

test_greedy: True
test_nepisode: 1
eval_nepisode: 1
test_interval: 400
eval_interval: 200  # evaluate target task interval
log_interval: 400
runner_log_interval: 400
learner_log_interval: 400
t_max: 2000
